/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description The frontend's auth/permission bootstrap (Step 9/10 of the Phase 10
         *     spec). display_name falls back to the actor identity string for
         *     principals with no app_users row (dev-mode, a static API_AUTH_TOKENS
         *     entry) - never a hard failure just to render a name.
         */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Work Items */
        get: operations["list_work_items_api_v1_work_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Work Item Queue Counts Route */
        get: operations["get_work_item_queue_counts_route_api_v1_work_items_counts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{work_item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Work Item */
        get: operations["get_work_item_api_v1_work_items__work_item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{work_item_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Work Item Attachments */
        get: operations["get_work_item_attachments_api_v1_work_items__work_item_id__attachments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{work_item_id}/conversation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Work Item Conversation */
        get: operations["get_work_item_conversation_api_v1_work_items__work_item_id__conversation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{work_item_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Work Item Draft */
        get: operations["get_work_item_draft_api_v1_work_items__work_item_id__draft_get"];
        /** Update Work Item Draft */
        put: operations["update_work_item_draft_api_v1_work_items__work_item_id__draft_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{work_item_id}/create-load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Load */
        post: operations["create_load_api_v1_work_items__work_item_id__create_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{work_item_id}/update-load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Load */
        post: operations["update_load_api_v1_work_items__work_item_id__update_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{work_item_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Work Item */
        post: operations["close_work_item_api_v1_work_items__work_item_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{work_item_id}/link-load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Work Item To Load */
        post: operations["link_work_item_to_load_api_v1_work_items__work_item_id__link_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Loads Endpoint
         * @description Legacy, unpaginated - kept for any existing caller relying on a
         *     bare list response. Prefer GET /loads/search for anything new (STEP 8:
         *     "avoid hidden breaking changes" - this endpoint's shape is unchanged;
         *     /search is additive, not a replacement of this route).
         */
        get: operations["list_loads_endpoint_api_v1_loads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loads/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Loads Endpoint
         * @description Server-side paginated, filtered, sorted, searched load collection -
         *     replaces loading the full `loads` table into a DataFrame and
         *     filtering/sorting/paginating it in Python (services/
         *     tms_data_service.py::load_tms_data's pattern).
         */
        get: operations["search_loads_endpoint_api_v1_loads_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loads/{load_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Load Endpoint */
        get: operations["get_load_endpoint_api_v1_loads__load_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loads/{load_id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Load Detail Endpoint
         * @description Richer than GET /loads/{load_id} - excludes timeline/communications/
         *     documents on purpose (STEP 9: "list DTO != detail DTO", and detail
         *     itself should not eagerly join large related collections either).
         *     Not replacing GET /loads/{load_id} (that route's shape is an existing
         *     contract - LoadSummary - left unchanged).
         */
        get: operations["get_load_detail_endpoint_api_v1_loads__load_id__detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loads/{load_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Load Timeline Endpoint */
        get: operations["get_load_timeline_endpoint_api_v1_loads__load_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loads/{load_id}/communications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Load Communications Endpoint */
        get: operations["get_load_communications_endpoint_api_v1_loads__load_id__communications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loads/{load_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Load Documents Endpoint */
        get: operations["get_load_documents_endpoint_api_v1_loads__load_id__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loads/{load_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition Load Endpoint */
        post: operations["transition_load_endpoint_api_v1_loads__load_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loads/{load_id}/assign-driver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign Driver Endpoint
         * @description Assignment without a status change: re-applies the load's current
         *     status through the same transactional apply_transition() path, so the
         *     driver/truck write and its audit row are still atomic.
         *
         *     new_status=None, not a status read here first - a status read by this
         *     router before apply_transition's row lock is taken could already be
         *     stale by the time the lock lands, and handing that stale value back
         *     as the transition target would make apply_transition validate it as
         *     a (spurious) backward move instead of the assignment-only request it
         *     actually is. See application/loads/commands.py::transition_load and
         *     services/dispatch_transition_service.py::apply_transition.
         */
        post: operations["assign_driver_endpoint_api_v1_loads__load_id__assign_driver_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attachments/{attachment_ref}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Attachment Content
         * @description Reads attachment bytes - the only place in the API that touches
         *     attachment content. attachment_ref is an opaque token (see
         *     application/work_items/queries.py attachment_ref()), resolved back to
         *     a server file path internally; the path itself is never accepted from
         *     or returned to the client.
         */
        get: operations["get_attachment_content_api_v1_attachments__attachment_ref__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inbox/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Inbox
         * @description Enqueues an inbox.sync job and returns immediately - does not fetch
         *     or parse email inline, does not wait for the inbox.process_message
         *     jobs the worker will enqueue once it processes this one. See
         *     application/inbox/commands.py::request_inbox_sync for the
         *     authorization boundary (Permission.WORK_ITEM_MANAGE, checked before
         *     any enqueue) and workers/inbox_handlers.py for what actually consumes
         *     this job.
         */
        post: operations["sync_inbox_api_v1_inbox_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Status
         * @description Safe worker_jobs fields only - never the raw payload (may contain
         *     message bodies/attachment metadata). See application/jobs/queries.py::
         *     get_worker_job_status; raises 404 via application.exceptions.
         *     NotFoundError if the job doesn't exist (handled by api/errors.py).
         */
        get: operations["get_job_status_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/worker/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Worker Status
         * @description Minimal operator/health view (Phase 7 STEP 5) - queue depths per
         *     status for both worker_jobs and outbox_events. Reflects database
         *     state only; does not and cannot prove the external scheduled runner
         *     (.github/workflows/process-jobs.yml) is actually running - see
         *     application/jobs/models.py::WorkerRuntimeStatus's docstring.
         */
        get: operations["get_worker_status_api_v1_worker_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Legacy
         * @description Legacy unversioned health check. Prefer GET /api/v1/health.
         */
        get: operations["health_legacy_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Loads Legacy
         * @description Legacy unversioned loads list. Prefer GET /api/v1/loads.
         */
        get: operations["list_loads_legacy_loads_get"];
        put?: never;
        /**
         * Create Load Legacy
         * @description Legacy unversioned load creation. Prefer POST /api/v1/work-items/{id}/create-load.
         */
        post: operations["create_load_legacy_loads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssignDriverIn */
        AssignDriverIn: {
            /** Driver */
            driver: string;
            /** Truck */
            truck?: string | null;
        };
        /**
         * AttachmentMetaOut
         * @description Deliberately excludes file_path - see application/work_items/models.py
         *     AttachmentMeta.attachment_ref for why.
         */
        AttachmentMetaOut: {
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Is Pdf */
            is_pdf: boolean;
            /** Attachment Ref */
            attachment_ref: string;
            /** Source Work Item Id */
            source_work_item_id?: number | null;
            /**
             * Source Message Id
             * @default
             */
            source_message_id: string;
            /**
             * Source Subject
             * @default
             */
            source_subject: string;
            /**
             * Source Received At
             * @default
             */
            source_received_at: string;
        };
        /** AttachmentSummaryOut */
        AttachmentSummaryOut: {
            /** Current */
            current: components["schemas"]["AttachmentMetaOut"][];
            /** Prior */
            prior: components["schemas"]["AttachmentMetaOut"][];
        };
        /** CloseWorkItemIn */
        CloseWorkItemIn: {
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** CommandResultOut */
        CommandResultOut: {
            /** Ok */
            ok: boolean;
            /** Work Item Id */
            work_item_id: number;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** CommunicationSummaryOut */
        CommunicationSummaryOut: {
            /** Message Count */
            message_count: number;
            /** Last Message At */
            last_message_at: string | null;
        };
        /** ConversationMessageOut */
        ConversationMessageOut: {
            /** Id */
            id: number;
            /** Source Received At */
            source_received_at: string | null;
            /** Email Direction */
            email_direction: string;
            /** Source Sender */
            source_sender: string;
            /** Source Subject */
            source_subject: string;
            /** Message Preview */
            message_preview: string;
            /** Conversation Status */
            conversation_status: string;
        };
        /** ConversationPageOut */
        ConversationPageOut: {
            /** Conversation Key */
            conversation_key: string;
            /** Messages */
            messages: components["schemas"]["ConversationMessageOut"][];
            /** Total Messages */
            total_messages: number;
        };
        /** CreateLoadIn */
        CreateLoadIn: {
            /** Approved Fields */
            approved_fields: {
                [key: string]: unknown;
            };
        };
        /** CreateLoadOut */
        CreateLoadOut: {
            /** Ok */
            ok: boolean;
            /** Load Id */
            load_id: number | null;
            /**
             * Review Status
             * @default
             */
            review_status: string;
        };
        /** FilterMetaOut */
        FilterMetaOut: {
            /** Queue */
            queue?: string | null;
            /** Service Flow */
            service_flow?: string | null;
            /** Customer */
            customer?: string | null;
            /** Search */
            search?: string | null;
            /** Subject */
            subject?: string | null;
            /** Status */
            status?: string | null;
            /** Attachment Status */
            attachment_status?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InboxSyncOut */
        InboxSyncOut: {
            /** Ok */
            ok: boolean;
            /** Job Id */
            job_id: number | null;
            /** Status */
            status: string;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** LinkLoadIn */
        LinkLoadIn: {
            /** Load Id */
            load_id: number;
        };
        /** LoadCommunicationOut */
        LoadCommunicationOut: {
            /** Id */
            id: number;
            /** Message Type */
            message_type: string;
            /** Direction */
            direction: string;
            /** Recipient */
            recipient: string;
            /** Message Body */
            message_body: string;
            /** Sent By */
            sent_by: string;
            /** Provider */
            provider: string;
            /** Delivery Status */
            delivery_status: string;
            /** Provider Message Id */
            provider_message_id: string;
            /** Created At */
            created_at: string | null;
        };
        /** LoadCommunicationPageOut */
        LoadCommunicationPageOut: {
            /** Items */
            items: components["schemas"]["LoadCommunicationOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Items */
            total_items: number;
            /** Total Pages */
            total_pages: number;
            /**
             * Sort By
             * @default
             */
            sort_by: string;
            /**
             * Sort Direction
             * @default desc
             */
            sort_direction: string;
        };
        /** LoadCreateRequest */
        LoadCreateRequest: {
            /**
             * Type
             * @default OTR Export
             */
            type: string | null;
            /** Booking Number */
            booking_number: string;
            /** Reference Number */
            reference_number?: string | null;
            /** Container Number */
            container_number?: string | null;
            /** Customer */
            customer?: string | null;
            /** Port */
            port?: string | null;
            /** Warehouse */
            warehouse?: string | null;
            /** Delivery Need Date */
            delivery_need_date?: string | null;
            /** Document Cutoff */
            document_cutoff?: string | null;
            /** Dispatcher Notes */
            dispatcher_notes?: string | null;
        };
        /** LoadDetailOut */
        LoadDetailOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Load Id */
            load_id: string;
            /** Booking Number */
            booking_number: string;
            /** Reference Number */
            reference_number: string;
            /** Container Number */
            container_number: string;
            /** Customer */
            customer: string;
            /** Port */
            port: string;
            /** Warehouse */
            warehouse: string;
            /** Address */
            address: string;
            /** Document Cutoff */
            document_cutoff: string | null;
            /** Delivery Need Date */
            delivery_need_date: string | null;
            /** Load Date */
            load_date: string | null;
            /** Lfd */
            lfd: string | null;
            /** Status */
            status: string;
            /** Driver Name */
            driver_name: string;
            /** Truck Assigned */
            truck_assigned: string;
            /** Chassis */
            chassis: string;
            /** Size */
            size: string;
            /** Billing Notes */
            billing_notes: string;
            /** Dispatcher Notes */
            dispatcher_notes: string;
            /** Invoice Status */
            invoice_status: string;
            /** Driver Pay Status */
            driver_pay_status: string;
            /** Closeout Stage */
            closeout_stage: string;
            /** Steamship Line */
            steamship_line: string;
            /** Vessel Name */
            vessel_name: string;
            /** Terminal */
            terminal: string;
            /** Pickup Appointment */
            pickup_appointment: string | null;
            /** Delivery Appointment */
            delivery_appointment: string | null;
            /** Empty Return Location */
            empty_return_location: string;
            /** Empty Return Date */
            empty_return_date: string | null;
            /** Parent Booking Key */
            parent_booking_key: string;
            /** Container Sequence */
            container_sequence: number | null;
            /** Container Total */
            container_total: number | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * LoadDocumentMetaOut
         * @description Deliberately excludes file_path - never a raw storage path in an
         *     API response (STEP 12).
         */
        LoadDocumentMetaOut: {
            /** Id */
            id: number;
            /** Document Type */
            document_type: string;
            /** Filename */
            filename: string;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Created At */
            created_at: string | null;
        };
        /** LoadListItemOut */
        LoadListItemOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Booking Number */
            booking_number: string;
            /** Reference Number */
            reference_number: string;
            /** Container Number */
            container_number: string;
            /** Customer */
            customer: string;
            /** Port */
            port: string;
            /** Warehouse */
            warehouse: string;
            /** Status */
            status: string;
            /** Driver Name */
            driver_name: string;
            /** Truck Assigned */
            truck_assigned: string;
            /** Delivery Need Date */
            delivery_need_date: string | null;
            /** Document Cutoff */
            document_cutoff: string | null;
            /** Invoice Status */
            invoice_status: string;
            /** Driver Pay Status */
            driver_pay_status: string;
            /** Updated At */
            updated_at: string | null;
        };
        /** LoadPageOut */
        LoadPageOut: {
            /** Items */
            items: components["schemas"]["LoadListItemOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Items */
            total_items: number;
            /** Total Pages */
            total_pages: number;
            /**
             * Sort By
             * @default
             */
            sort_by: string;
            /**
             * Sort Direction
             * @default desc
             */
            sort_direction: string;
        };
        /** LoadSummaryOut */
        LoadSummaryOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Booking Number */
            booking_number: string;
            /** Reference Number */
            reference_number: string;
            /** Container Number */
            container_number: string;
            /** Customer */
            customer: string;
            /** Status */
            status: string;
            /** Driver Name */
            driver_name: string;
            /** Truck Assigned */
            truck_assigned: string;
            /** Updated At */
            updated_at: string | null;
        };
        /** LoadTimelineEventOut */
        LoadTimelineEventOut: {
            /** Event Type */
            event_type: string;
            /** Title */
            title: string;
            /** Details */
            details: string;
            /** Actor */
            actor: string;
            /** Created At */
            created_at: string | null;
        };
        /** LoadTimelinePageOut */
        LoadTimelinePageOut: {
            /** Items */
            items: components["schemas"]["LoadTimelineEventOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Items */
            total_items: number;
            /** Total Pages */
            total_pages: number;
            /**
             * Sort By
             * @default
             */
            sort_by: string;
            /**
             * Sort Direction
             * @default desc
             */
            sort_direction: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginOut */
        LoginOut: {
            /** Token */
            token: string;
            /** Actor */
            actor: string;
            /** Role */
            role: string;
        };
        /** MeOut */
        MeOut: {
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /** Permissions */
            permissions: string[];
        };
        /** OrderDraftOut */
        OrderDraftOut: {
            /** Exists */
            exists: boolean;
            /** Draft Status */
            draft_status?: string | null;
            /** Booking Number */
            booking_number?: string | null;
            /** Container Number */
            container_number?: string | null;
            /** Container Qty */
            container_qty?: number | null;
            /** Service Flow */
            service_flow?: string | null;
        };
        /** OrderDraftSummaryOut */
        OrderDraftSummaryOut: {
            /** Exists */
            exists: boolean;
            /** Draft Status */
            draft_status?: string | null;
            /** Booking Number */
            booking_number?: string | null;
            /** Container Number */
            container_number?: string | null;
            /** Container Qty */
            container_qty?: number | null;
            /** Service Flow */
            service_flow?: string | null;
        };
        /** QueueCountOut */
        QueueCountOut: {
            /** Queue */
            queue: string;
            /** Count */
            count: number;
        };
        /** SortMetaOut */
        SortMetaOut: {
            /** Sort By */
            sort_by: string;
            /** Sort Direction */
            sort_direction: string;
        };
        /** TransitionLoadIn */
        TransitionLoadIn: {
            /** New Status */
            new_status: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Driver */
            driver?: string | null;
            /** Truck */
            truck?: string | null;
            /**
             * Override
             * @default false
             */
            override: boolean;
            /**
             * Override Reason
             * @default
             */
            override_reason: string;
        };
        /** TransitionResultOut */
        TransitionResultOut: {
            /** Ok */
            ok: boolean;
            /** Reason */
            reason: string;
            /** Status */
            status: string;
            /** Closeout Stage */
            closeout_stage: string;
        };
        /** UpdateLoadIn */
        UpdateLoadIn: {
            /** Load Id */
            load_id: number;
            /** Approved Fields */
            approved_fields: {
                [key: string]: unknown;
            };
            /**
             * Fill Blank Only
             * @default true
             */
            fill_blank_only: boolean;
        };
        /** UpdateLoadOut */
        UpdateLoadOut: {
            /** Ok */
            ok: boolean;
            /** Load Id */
            load_id: number | null;
            /**
             * Updated Fields
             * @default []
             */
            updated_fields: string[];
            /**
             * Skipped Fields
             * @default []
             */
            skipped_fields: string[];
        };
        /** UpdateOrderDraftIn */
        UpdateOrderDraftIn: {
            /** Fields */
            fields: {
                [key: string]: unknown;
            };
        };
        /** UpdateOrderDraftOut */
        UpdateOrderDraftOut: {
            /** Ok */
            ok: boolean;
            /** Conversation Key */
            conversation_key: string;
            /** Updated Fields */
            updated_fields: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkItemDetailOut */
        WorkItemDetailOut: {
            /** Id */
            id: number;
            /** Source Sender */
            source_sender: string;
            /** Source Subject */
            source_subject: string;
            /** Source Received At */
            source_received_at: string | null;
            /** Original Email Body */
            original_email_body: string;
            /** Parsed Data */
            parsed_data: {
                [key: string]: unknown;
            };
            /** Request Type */
            request_type: string;
            /** Matched Load Id */
            matched_load_id: number | null;
            /** Conversation Key */
            conversation_key: string;
            /** Review Status */
            review_status: string;
            /** Confidence Score */
            confidence_score: number;
            attachments: components["schemas"]["AttachmentSummaryOut"];
            communication_summary: components["schemas"]["CommunicationSummaryOut"];
            order_draft: components["schemas"]["OrderDraftSummaryOut"];
            /** Allowed Actions */
            allowed_actions: string[];
        };
        /** WorkItemPageOut */
        WorkItemPageOut: {
            /** Items */
            items: components["schemas"]["WorkItemSummaryOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Items */
            total_items: number;
            /** Total Pages */
            total_pages: number;
            sort: components["schemas"]["SortMetaOut"];
            filters: components["schemas"]["FilterMetaOut"];
        };
        /** WorkItemQueueCountsOut */
        WorkItemQueueCountsOut: {
            /** Counts */
            counts: components["schemas"]["QueueCountOut"][];
        };
        /** WorkItemSummaryOut */
        WorkItemSummaryOut: {
            /** Id */
            id: number;
            /** Created At */
            created_at: string | null;
            /** Source Received At */
            source_received_at: string | null;
            /** Source Subject */
            source_subject: string;
            /** Source Sender */
            source_sender: string;
            /** Email Direction */
            email_direction: string;
            /** Request Type */
            request_type: string;
            /** Work Queue */
            work_queue: string;
            /** Department Lane */
            department_lane: string;
            /** Review Status */
            review_status: string;
            /** Confidence Score */
            confidence_score: number;
            /** Matched Load Id */
            matched_load_id: number | null;
            /** Conversation Key */
            conversation_key: string;
            /** Case Id */
            case_id: number | null;
            /** Customer */
            customer: string;
            /** Booking Number */
            booking_number: string;
            /** Container Number */
            container_number: string;
            /** Reference Number */
            reference_number: string;
            /** Service Flow */
            service_flow: string;
            /** Attachment Count */
            attachment_count: number;
        };
        /** WorkerJobStatusOut */
        WorkerJobStatusOut: {
            /** Id */
            id: number;
            /** Job Type */
            job_type: string;
            /** Status */
            status: string;
            /** Attempt Count */
            attempt_count: number;
            /** Created At */
            created_at: string | null;
            /** Claimed At */
            claimed_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Last Error */
            last_error: string | null;
        };
        /** WorkerRuntimeStatusOut */
        WorkerRuntimeStatusOut: {
            /** Worker Jobs By Status */
            worker_jobs_by_status: {
                [key: string]: number;
            };
            /** Outbox Events By Status */
            outbox_events_by_status: {
                [key: string]: number;
            };
            /** Checked At */
            checked_at: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_work_items_api_v1_work_items_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                sort_by?: string;
                sort_direction?: string;
                queue?: string | null;
                service_flow?: string | null;
                customer?: string | null;
                search?: string | null;
                subject?: string | null;
                status?: string | null;
                attachment_status?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItemPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_item_queue_counts_route_api_v1_work_items_counts_get: {
        parameters: {
            query?: {
                service_flow?: string | null;
                customer?: string | null;
                search?: string | null;
                subject?: string | null;
                status?: string | null;
                attachment_status?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItemQueueCountsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_item_api_v1_work_items__work_item_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                work_item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItemDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_item_attachments_api_v1_work_items__work_item_id__attachments_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                work_item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_item_conversation_api_v1_work_items__work_item_id__conversation_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                work_item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_item_draft_api_v1_work_items__work_item_id__draft_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                work_item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_work_item_draft_api_v1_work_items__work_item_id__draft_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                work_item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderDraftIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateOrderDraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_load_api_v1_work_items__work_item_id__create_load_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                work_item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLoadIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateLoadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_load_api_v1_work_items__work_item_id__update_load_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                work_item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLoadIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateLoadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_work_item_api_v1_work_items__work_item_id__close_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                work_item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseWorkItemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_work_item_to_load_api_v1_work_items__work_item_id__link_load_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                work_item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkLoadIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_loads_endpoint_api_v1_loads_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_loads_endpoint_api_v1_loads_search_get: {
        parameters: {
            query?: {
                status?: string | null;
                service_flow?: string | null;
                customer?: string | null;
                driver_name?: string | null;
                port?: string | null;
                warehouse?: string | null;
                invoice_status?: string | null;
                search?: string | null;
                delivery_after?: string | null;
                delivery_before?: string | null;
                sort?: string;
                direction?: string;
                page?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_load_endpoint_api_v1_loads__load_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                load_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_load_detail_endpoint_api_v1_loads__load_id__detail_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                load_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_load_timeline_endpoint_api_v1_loads__load_id__timeline_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                load_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadTimelinePageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_load_communications_endpoint_api_v1_loads__load_id__communications_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                load_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadCommunicationPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_load_documents_endpoint_api_v1_loads__load_id__documents_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                load_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadDocumentMetaOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_load_endpoint_api_v1_loads__load_id__transition_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                load_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionLoadIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_driver_endpoint_api_v1_loads__load_id__assign_driver_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                load_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignDriverIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attachment_content_api_v1_attachments__attachment_ref__content_get: {
        parameters: {
            query: {
                work_item_id: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                attachment_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_inbox_api_v1_inbox_sync_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxSyncOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_status_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerJobStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_worker_status_api_v1_worker_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerRuntimeStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_legacy_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_loads_legacy_loads_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_load_legacy_loads_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
