# Copy this file to .streamlit/secrets.toml
# For Supabase, use Project Settings > Database > Connection string.
# Use the SQLAlchemy form beginning with postgresql+psycopg2://

DATABASE_URL = "postgresql://postgres.tzmdapakwdgvckavoxrr:CaliTransTMS2026@aws-1-us-east-2.pooler.supabase.com:6543/postgres"


YAHOO_EMAIL = "dispatch@calitranscorp.com"
YAHOO_APP_PASSWORD = "fjqutqjsrchedfih"

IMAP_SERVER = "imap.mail.yahoo.com"
IMAP_PORT = "993"

SMTP_HOST = "smtp.mail.yahoo.com"
SMTP_PORT = "465"
SMTP_USER = "dispatch@calitranscorp.com"
SMTP_PASSWORD = "fjqutqjsrchedfih"
DISPATCH_EMAIL = "dispatch@calitranscorp.com"

COMPANY_NAME = "CaliTrans"

PORT_HOUSTON_CLIENT_ID="pha-calitrans"
PORT_HOUSTON_CLIENT_SECRET = "5DBUXHrFYCpVjfkWwwFPJQZLx44bzVv3"
PORT_HOUSTON_OPERATOR="POHA"
