# Copy this file to .streamlit/secrets.toml
# For Supabase, use Project Settings > Database > Connection string.
# Use the SQLAlchemy form beginning with postgresql+psycopg2://

DATABASE_URL = "postgresql://postgres.tzmdapakwdgvckavoxrr:CaliTransTMS2026@aws-1-us-east-2.pooler.supabase.com:6543/postgres"

EMAIL_ADDRESS= "vreza75@gmail.com"
EMAIL_APP_PASSWORD = "uxkp lfdv kjvu cdhr"
EMAIL_IMAP_SERVER = "imap.gmail.com"

SMTP_HOST="smtp.gmail.com"
SMTP_PORT="587"
SMTP_USER="vreza75@gmail.com"
SMTP_PASSWORD="uxkp lfdv kjvu cdhr"
DISPATCH_EMAIL="dispatch@calitranscorp.com"
COMPANY_NAME="CaliTrans"
